EXACT_ALIASES: dict[str, str] = {
    "старт": "start",
    "бот": "alive",
    "игра": "game",
    "роль": "role",
    "кто я": "me",
    "кто ты": "alive",
    "помощь": "help",
    "рег": "announce_reg",
    "анрег": "announce_unreg",
    "репутация": "rep",
    "мой рейтинг": "rep",
    "достижения": "achievements",
    "ачивки": "achievements",
    "мои достижения": "achievements",
    "мои ачивки": "achievements",
    "актив": "active",
    "когда был": "lastseen",
    "когда была": "lastseen",
    "баланс": "eco",
    "ферма": "farm",
    "магазин": "shop",
    "инвентарь": "inventory",
    "тап": "tap",
    "дейлик": "daily",
    "лотерея": "lottery",
    "рынок": "market",
    "жмых": "zhmyh",
    "рост": "growth",
    "профиль": "growth",
    "дрочка": "growth_action",
    "подрочить": "growth_action",
    "дрочить": "growth_action",
    "отношения": "relation",
    "мои отношения": "relation",
    "брак": "relation",
    "мой брак": "marriage",
    "браки": "marriages",
    "пара": "pair",
    "жениться": "marry",
    "расстаться": "breakup",
    "развод": "divorce",
    "любовь": "love",
    "забота": "care",
    "свидание": "date",
    "подарок": "gift",
    "поддержка": "support",
    "флирт": "flirt",
    "сюрприз": "surprise",
    "клятва": "vow",
    "шипперим": "shipperim",
}
